package com.ivan.sertic.model;

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

@Entity
public class Users {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    // TODO this must also be autogenerated hint use anotations

    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "org.hibernate.id.UUIDGenerator")
    private UUID externalUserId;

    private String username;

    private String password;

    @OneToMany(
            mappedBy =  "user",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private Set<Diary> diaries = new HashSet<>();

    @OneToMany(
            mappedBy = "user",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private Set<Library> libraries = new HashSet<>();

   /*  --NOT SURE ABOUT THIS CTOR--
        public Users(String username, String password) {
        this.username = username;
        this.password = password;
    }*/

    public void addDiary(Diary diary){
        diaries.add(diary);
        diary.setUser(this);
    }

    public void removeDiary(Diary diary){
        diaries.remove(diary);
        diary.setUser(null);
    }

    public void addLibrary(Library library){
        libraries.add(library);
        library.setUser(this);
    }

    public void removeLibrary(Library library){
        libraries.remove(library);
        library.setUser(null);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public UUID getExternalId() {
        return externalUserId;
    }

    public void setExternalId(UUID externalId) {
        this.externalUserId = externalId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


}
